// Autogenerated USMLE Step 1 Comprehensive Question Bank Manifest
// Contains metadata for Pathology (2,100 Qs), Pharmacology (1,350 Qs), Biochemistry & Genetics (3,450 Qs), Physiology (5,100 Qs), and Anatomy & Embryology (3,000 Qs)

window.USMLE_QUESTIONS = window.USMLE_QUESTIONS || [];

window.USMLE_DISCIPLINES = [
  {
    "id": "Pathology",
    "name": "Pathology",
    "step": 1,
    "count": 2100,
    "status": "active",
    "description": "General and systemic pathology (14 chapters)"
  },
  {
    "id": "Pharmacology",
    "name": "Pharmacology",
    "step": 1,
    "count": 1350,
    "status": "active",
    "description": "Comprehensive preclinical pharmacology (9 chapters)"
  },
  {
    "id": "Biochemistry",
    "name": "Biochemistry & Genetics",
    "step": 1,
    "count": 3450,
    "status": "active",
    "description": "Comprehensive biochemistry, metabolism, molecular biology, and medical genetics (23 chapters)"
  },
  {
    "id": "Physiology",
    "name": "Physiology",
    "step": 1,
    "count": 5100,
    "status": "active",
    "description": "Comprehensive cellular, neuromuscular, organ system, and integrative physiology (34 chapters)"
  },
  {
    "id": "Anatomy",
    "name": "Anatomy & Embryology",
    "step": 1,
    "count": 3000,
    "status": "active",
    "description": "Comprehensive gross anatomy, embryology, histology, and neuroscience (20 chapters)"
  }
];
